In [1]:
import streamlit as st
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame(
    np.random.rand(100, 2)/[50,50] + [35.69, 139.70],
    columns=['lat', 'lon']
)
df

           a         b         c
0   0.769922  0.427930  0.446099
1   0.599402  0.217283  0.712249
2   0.147139  0.462408  0.460336
3   0.459384  0.153567  0.936392
4   0.031974  0.467330  0.350136
5   0.559117  0.398238  0.441139
6   0.392509  0.126970  0.258378
7   0.555031  0.549732  0.528754
8   0.460765  0.127684  0.799214
9   0.040031  0.885359  0.213842
10  0.308173  0.099963  0.108439
11  0.747564  0.739719  0.061267
12  0.791454  0.759325  0.003981
13  0.026440  0.334651  0.419669
14  0.748196  0.802814  0.999403
15  0.515808  0.070916  0.829754
16  0.388351  0.046437  0.670756
17  0.637145  0.635592  0.386071
18  0.845528  0.298394  0.545814
19  0.731222  0.963276  0.361852